### ISSUE TITLE
A bunch of testing resources

### ISSUE THREAD

**Issue by CarlosMChica** [sccommunity/sc-newsletter-issues#21]
- Codurance - Naming test classes and methods : http://codurance.com/2014/12/13/naming-test-classes-and-methods/
- J.B. - TDD is Not Magic - http://blog.jbrains.ca/permalink/tdd-is-not-magic
- (Discussion between J.B. and S. Mancuso) - TDD and Software Design - https://www.youtube.com/watch?v=ty3p5VDcoOI
- S. Mancuso - DOES TDD REALLY LEAD TO GOOD DESIGN? - http://codurance.com/2015/05/12/does-tdd-lead-to-good-design/

**Comment by alebaffa** [comment]
Hey thanks! I was exactly thinking about creating "thematic" sections in the next newsletter :+1: 
In general, I would tend to not post too many old things written by Sandro Mancuso and Codurance, just because I think that most of the people who are registered to the newsletter already read all of them.

**Comment by CarlosMChica** [comment]
That's alright. 

I'll share the resources I find useful and you can filter out whatever you think is not interesting enough. However, I don't have a problem to just omit stuff written by Sandro and Codurance or any other content.

Please let me know.

**Comment by alebaffa** [comment]
Please, continue to post everything you find useful. Btw, not all the people registered are from the Slack community. What I said is a general indication, I just don't want to post too much things from them in one shot :) But, please don't stop. You're helping me so much!

**Comment by CarlosMChica** [comment]
will do

**Comment by alebaffa** [comment]
@CarlosMChica I've just updated the contribution guide. Thanks to a discussion had in #18 I decided to stop using issues for suggesting links, and use only pull requests (so that Travis can check for duplicates automatically). So, can you please create a PR against the file _newsletter-11-open.md_, please? Thank you!

**Comment by alebaffa** [comment]
So, I am closing this issue.
