### ISSUE TITLE
Testing Time and controlling System.currentTimeMillis

### ISSUE THREAD

**Issue by blundell** [sccommunity/sc-newsletter-issues#26]
Rather a simple issue compared to most "software craftsmanship" posts, but trying to teach all levels of people the skills of coding requires all levels of blog posts.

Hope someone finds this useful when trying to test time:

http://blog.blundellapps.co.uk/how-to-test-time-and-control-system-currenttimemillis/

> This post explains how to control time and specifically control System.currentTimeMillis. To make your code more flexible, maintainable and in the end testable! Showing an example application that uses time to define different behaviour for the app in the morning and in the evening. Going on to unit test this in a robust manner.

**Comment by alebaffa** [comment]
Interesting, thank you!

**Comment by alebaffa** [comment]
@blundell I've just updated the contribution guide. Thanks to a discussion had in #18 I decided to stop using issues for suggesting links, and use only pull requests (so that Travis can check for duplicates automatically). So, can you please create a PR against the file _newsletter-11-open.md_, please? Thank you!

**Comment by alebaffa** [comment]
So, I'm closing this issue.

**Comment by blundell** [comment]
Fixed in https://github.com/alebaffa/sc-newsletter-issues/pull/27 :-)
